//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoSoftware.MonoX.Pages.SocialNetworking {
    
    
    public partial class Groups {
        
        /// <summary>
        /// leftPartZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.PortalWebPartZoneTableless leftPartZone;
        
        /// <summary>
        /// ctlGroupContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.ModuleGallery.SocialNetworking.GroupContainer ctlGroupContainer;
        
        /// <summary>
        /// plhHome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder plhHome;
        
        /// <summary>
        /// rightWebPartZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.PortalWebPartZoneTableless rightWebPartZone;
        
        /// <summary>
        /// ctlGroupInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.ModuleGallery.SocialNetworking.GroupInfo ctlGroupInfo;
        
        /// <summary>
        /// ctlSearchGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.ModuleGallery.SocialNetworking.GroupSearch ctlSearchGroups;
        
        /// <summary>
        /// ctlGroupMemberList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.ModuleGallery.SocialNetworking.GroupMemberList ctlGroupMemberList;
        
        /// <summary>
        /// ctlPeopleSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.ModuleGallery.SocialNetworking.GroupPeopleSearch ctlPeopleSearch;
        
        /// <summary>
        /// ctlInvitationsSent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.ModuleGallery.SocialNetworking.GroupInvitationList ctlInvitationsSent;
        
        /// <summary>
        /// ctlInvitationsReceived control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.ModuleGallery.SocialNetworking.GroupInvitationList ctlInvitationsReceived;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new MonoSoftware.MonoX.BaseMasterPage Master {
            get {
                return ((MonoSoftware.MonoX.BaseMasterPage)(base.Master));
            }
        }
    }
}
