//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoSoftware.MonoX.Pages {
    
    
    public partial class Contact {
        
        /// <summary>
        /// contentPartZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.PortalWebPartZoneTableless contentPartZone;
        
        /// <summary>
        /// ctlContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.ModuleGallery.ContactFormModule ctlContact;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new MonoSoftware.MonoX.BaseMasterPage Master {
            get {
                return ((MonoSoftware.MonoX.BaseMasterPage)(base.Master));
            }
        }
    }
}
