//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoSoftware.MonoX.Pages {
    
    
    public partial class Default {
        
        /// <summary>
        /// topPartZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.PortalWebPartZoneTableless topPartZone;
        
        /// <summary>
        /// editor2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.ModuleGallery.MonoXHtmlEditor editor2;
        
        /// <summary>
        /// ctlSlideShow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.ModuleGallery.SlideShow ctlSlideShow;
        
        /// <summary>
        /// middlePartZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.PortalWebPartZoneTableless middlePartZone;
        
        /// <summary>
        /// editor3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.ModuleGallery.MonoXHtmlEditor editor3;
        
        /// <summary>
        /// bottomWebPartZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.PortalWebPartZoneTableless bottomWebPartZone;
        
        /// <summary>
        /// editor1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MonoSoftware.MonoX.ModuleGallery.MonoXHtmlEditor editor1;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new MonoSoftware.MonoX.BaseMasterPage Master {
            get {
                return ((MonoSoftware.MonoX.BaseMasterPage)(base.Master));
            }
        }
    }
}
